import type { Metadata, Viewport } from "next";
import { Inter } from "next/font/google";
import { RouteProvider } from "@/providers/router-provider";
import { Theme } from "@/providers/theme";
import "@/styles/globals.css";
import { cx } from "@/utils/cx";
import { ThemeToggleFab } from "@/components/theme/theme-toggle-fab";

const inter = Inter({
    subsets: ["latin"],
    display: "swap",
    variable: "--font-inter",
});

export const metadata: Metadata = {
    title: "Empedia",
    description: "Generated by Untitled UI CLI",
};

export const viewport: Viewport = {
    themeColor: "#10b981",
    colorScheme: "light dark",
};

import { MarketingLayoutWrapper } from "@/components/marketing/layout-wrapper";

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={cx(inter.variable, "bg-primary antialiased")}>
                <RouteProvider>
                    <Theme>
                        <MarketingLayoutWrapper>
                            {children}
                        </MarketingLayoutWrapper>
                        <ThemeToggleFab />
                    </Theme>
                </RouteProvider>
            </body>
        </html>
    );
}
